export const VBA_GROUPE_RUBRIQUE_TRANSPORT_ID = 1;
export const VBA_GROUPE_RUBRIQUE_CANTINE_ID = 2;
export const VBA_GROUPE_RUBRIQUE_SPORT_LOISIR_ID = 3;

export const ACTIVITE_POINTAGE_APPRENANT_ID = "ASC001";
export const ACTIVITE_POINTAGE_CANTINE_ID = "ASC002";
export const ACTIVITE_POINTAGE_CAR_ID = "ASC003";
export const ACTIVITE_POINTAGE_PERSONNEL_ID = "ASC004";

export const ACTIVITE_CONTROLE_FRAIS_SCOLAIRE_ID = "ASC005";
export const ACTIVITE_CONTROLE_CANTINE_ID = "ASC006";
export const ACTIVITE_CONTROLE_TRANSPORT_ID = "ASC007";